import { StyleSheet, Platform } from 'react-native';
import { colors } from '../theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  tecladoContainer: {
    flex: 1,
  },
  conteudoRolagem: {
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 30,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100%',
  },
  cartao: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: colors.cardBackground,
    borderWidth: 1.2,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 28,
    paddingTop: 20,
    paddingBottom: 26,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
  },
  logo: {
    width: 38,
    height: 38,
    marginBottom: 10,
  },
  titulo: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 20,
  },
  formulario: {
    width: '100%',
    gap: 16,
  },
  campo: {
    width: '100%',
  },
  rotulo: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  campoTexto: {
    width: '100%',
    height: 42,
    borderWidth: 1,
    borderColor: colors.borderInput,
    borderRadius: 5,
    backgroundColor: colors.inputBackground,
    paddingHorizontal: 12,
    fontSize: 12,
    color: colors.textPrimary,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none', outlineWidth: 0 } : {}),
  },
  botaoEsqueceuSenha: {
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  textoEsqueceuSenha: {
    fontSize: 11,
    color: colors.primary,
    fontWeight: '500',
  },
  botaoEntrar: {
    width: '60%',
    height: 46,
    marginTop: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    elevation: 3,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
  },
  textoBotaoEntrar: {
    color: colors.white,
    fontSize: 14,
    fontWeight: 'bold',
  },
  divisorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    marginTop: 28,
    marginBottom: 16,
  },
  linhaDivisor: {
    flex: 1,
    height: 1,
    backgroundColor: colors.maroon,
    opacity: 0.5,
  },
  textoDivisor: {
    marginHorizontal: 12,
    fontSize: 13,
    color: '#333333',
    fontWeight: '500',
  },
  botaoGoogle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    borderRadius: 8,
    width: '75%',
    height: 44,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 24,
  },
  iconeGoogleContainer: {
    marginRight: 10,
  },
  textoBotaoGoogle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333333',
  },
  rodapeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoRodape: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  linkRodape: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
});

export default styles;
