import { StyleSheet, Platform } from 'react-native';
import { colors } from '../theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  tecladoContainer: {
    flex: 1,
  },
  cabecalho: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
  },
  botaoFechar: {
    width: 36,
    height: 36,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  tituloCabecalho: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  espacadorCabecalho: {
    width: 36,
  },
  conteudoRolagem: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
    alignItems: 'center',
  },
  cartao: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
    padding: 16,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tituloCartao: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  campoTextoArea: {
    height: 180,
    backgroundColor: colors.inputBgLight,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    padding: 12,
    fontSize: 14,
    color: colors.textPrimary,
    textAlignVertical: 'top',
    ...(Platform.OS === 'web' ? { outlineStyle: 'none', outlineWidth: 0 } : {}),
  },
  previaImagemWrapper: {
    width: '100%',
    height: 190,
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 12,
    position: 'relative',
    backgroundColor: colors.badgePink,
  },
  previaImagem: {
    width: '100%',
    height: '100%',
  },
  botaoRemoverImagem: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: colors.white,
    borderRadius: 13,
  },
  containerEtiquetasSelecionadas: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  etiqueta: {
    backgroundColor: colors.badgePink,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderSubtle,
  },
  textoEtiqueta: {
    fontSize: 11,
    color: colors.maroon,
    fontWeight: '600',
  },
  etiquetaCarregando: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF0F2',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFCCD5',
    gap: 6,
  },
  textoEtiquetaCarregando: {
    fontSize: 11,
    color: colors.primaryVariant,
    fontWeight: '600',
  },
  containerInterruptorGps: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF5F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 14,
    borderWidth: 1,
    borderColor: '#F3CCD4',
  },
  grupoTextoGps: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    paddingRight: 10,
  },
  conteudoTextoGps: {
    marginLeft: 8,
    flex: 1,
  },
  tituloInterruptorGps: {
    fontSize: 13,
    fontWeight: '700',
    color: '#333333',
  },
  subtituloInterruptorGps: {
    fontSize: 11,
    color: colors.textGrey,
    marginTop: 1,
  },
  linhaOpcoes: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  itemOpcao: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  textoOpcao: {
    fontSize: 12,
    color: colors.primaryVariant,
    fontWeight: '600',
  },
  botaoPublicar: {
    width: '65%',
    maxWidth: 240,
    height: 48,
    backgroundColor: colors.primaryVariant,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  textoBotaoPublicar: {
    color: colors.white,
    fontSize: 15,
    fontWeight: 'bold',
  },
});

export default styles;
