import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  cabecalho: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
  },
  botaoCabecalho: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tituloCabecalho: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  rolagemTela: {
    flex: 1,
  },
  conteudoRolagem: {
    paddingBottom: 20,
  },
  secaoAvatar: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 8,
  },
  circuloAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    position: 'relative',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  imagemAvatar: {
    width: 94,
    height: 94,
    borderRadius: 47,
  },
  marcadorAvatar: {
    width: 94,
    height: 94,
    borderRadius: 47,
    backgroundColor: colors.borderSubtle,
  },
  distintivoCamera: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: colors.white,
    borderRadius: 12,
    width: 26,
    height: 26,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.primary,
    elevation: 2,
  },
  informacoesUsuario: {
    alignItems: 'center',
    marginBottom: 16,
  },
  nomeUsuario: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    letterSpacing: -0.3,
  },
  arrobaUsuario: {
    fontSize: 13,
    color: colors.maroon,
    marginTop: 2,
  },
  linhaEstatisticas: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
    gap: 24,
  },
  itemEstatistica: {
    alignItems: 'center',
  },
  numeroEstatistica: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  rotuloEstatistica: {
    fontSize: 10,
    color: '#666666',
    marginTop: 2,
  },
  containerBiografia: {
    alignItems: 'center',
    marginBottom: 14,
    paddingHorizontal: 20,
  },
  textoBiografia: {
    fontSize: 12,
    color: '#222222',
    textAlign: 'center',
    lineHeight: 16,
  },
  linhaAbas: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 6,
  },
  botaoAba: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignItems: 'center',
    borderBottomWidth: 2.5,
    borderBottomColor: 'transparent',
  },
  botaoAbaAtiva: {
    borderBottomColor: colors.primary,
  },
  divisorAbas: {
    width: '100%',
    height: 1,
    backgroundColor: colors.borderSubtle,
    opacity: 0.5,
  },
  gradePublicacoes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    rowGap: 14,
  },
  cartaoGradePublicacao: {
    width: '48%',
    height: 180,
    backgroundColor: colors.badgePink,
    borderWidth: 1.5,
    borderColor: colors.primary,
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  imagemPublicacao: {
    width: '100%',
    height: '100%',
  },
  marcadorPublicacao: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.badgePink,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoMarcadorPublicacao: {
    fontSize: 12,
    color: colors.maroon,
    textAlign: 'center',
  },
  listaPublicacoes: {
    paddingHorizontal: 16,
    paddingTop: 14,
    gap: 14,
  },
  cartaoListaPublicacao: {
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1.2,
    borderColor: colors.borderSubtle,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  imagemListaPublicacao: {
    width: '100%',
    height: 200,
  },
  infoListaPublicacao: {
    padding: 12,
  },
  legendaListaPublicacao: {
    fontSize: 14,
    color: colors.textDark,
    lineHeight: 19,
    marginBottom: 8,
  },
  acoesListaPublicacao: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemAcaoLista: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoAcaoLista: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.textDark,
    marginLeft: 5,
  },
  containerSalvos: {
    paddingBottom: 20,
  },
  caixaSalvosVazia: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
    paddingHorizontal: 30,
  },
  tituloSalvosVazio: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textDark,
    marginTop: 12,
    marginBottom: 6,
  },
  subtituloSalvosVazio: {
    fontSize: 13,
    color: '#666666',
    textAlign: 'center',
    lineHeight: 18,
  },
});

export default styles;
