import { StyleSheet, Platform } from 'react-native';
import { colors } from '../theme/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.backgroundPost,
  },
  conteudo: {
    paddingBottom: 20,
  },
  cabecalho: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  titulo: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  usuarioContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 18,
    marginTop: 8,
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.placeholderGray,
    marginRight: 14,
  },
  imagemAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    marginRight: 14,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  nomeAutor: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  linhaMetadados: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
    gap: 4,
  },
  horarioPublicacao: {
    fontSize: 10,
    color: '#333333',
  },
  linhaLocalizacao: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  separadorPonto: {
    fontSize: 10,
    color: colors.primaryVariant,
    marginRight: 1,
  },
  textoLocalizacaoDetalhe: {
    fontSize: 10,
    color: colors.primaryVariant,
    fontWeight: '600',
  },
  textoPublicacao: {
    fontSize: 15,
    color: colors.textPrimary,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 10,
  },
  imagemPublicacao: {
    height: 220,
    marginHorizontal: 16,
    borderRadius: 12,
    backgroundColor: colors.badgePink,
    overflow: 'hidden',
  },
  acoesBarra: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 10,
  },
  acoesEsquerda: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
  },
  itemAcao: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  contadorAcao: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  tituloComentarios: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 10,
  },
  cartaoComentario: {
    flexDirection: 'row',
    backgroundColor: colors.cardComment,
    marginHorizontal: 16,
    borderRadius: 8,
    padding: 10,
    minHeight: 84,
    marginBottom: 12,
    shadowColor: colors.darkMaroon,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  marcadorAvatarComentario: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.maroon,
    marginRight: 12,
  },
  imagemAvatarComentario: {
    width: 42,
    height: 42,
    borderRadius: 21,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: colors.primary,
  },
  conteudoComentario: {
    flex: 1,
    paddingTop: 1,
  },
  nomeComentario: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.textPrimary,
  },
  horarioComentario: {
    fontSize: 9,
    color: '#222222',
    marginTop: 2,
  },
  textoConteudoComentario: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textPrimary,
    marginTop: 8,
  },
  formularioComentario: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    marginHorizontal: 16,
    marginTop: 17,
    borderRadius: 7,
    paddingHorizontal: 12,
    height: 57,
    marginBottom: 10,
    borderWidth: 0,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  campoTextoComentario: {
    flex: 1,
    height: '100%',
    fontSize: 13,
    color: colors.textPrimary,
    borderWidth: 0,
    ...(Platform.OS === 'web' ? { outlineStyle: 'none', outlineWidth: 0 } : {}),
  },
  botaoEnviarComentario: {
    padding: 6,
  },
});

export default styles;
